name: Check

on: [push, pull_request]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew check coveralls --stacktrace
      - name: Show Reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: reports
          path: build/reports/
