name: Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Decode PGP
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'secret.pgp'
          encodedString: ${{ secrets.SIGNING_SECRET_KEY_BASE64 }}
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - uses: gradle/gradle-build-action@v3
      - env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_PATH: ${{ steps.write_file.outputs.filePath }}
        run: ./gradlew gitPublishPush publishToSonatype closeAndReleaseSonatypeStagingRepository "-Pversion=${{ steps.version.outputs.tag }}" -Prelease=true "-Dorg.ajoberstar.grgit.auth.username=${{ secrets.GH_PAGES_TOKEN }}" --stacktrace
